# Generated by Django 4.2.7 on 2023-12-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=255, verbose_name='Math Expression')),
                ('answer', models.FloatField(verbose_name='Answer')),
            ],
        ),
    ]
